[package]
name = "blaze-serde"
version = "0.1.0"
edition = "2021"

[features]
default = ["prost/no-recursion-limit"]

[dependencies]
arrow = { workspace = true }
base64 = "*"
datafusion = { workspace = true }
datafusion-ext-commons = { workspace = true }
datafusion-ext-exprs = { workspace = true }
datafusion-ext-functions = { workspace = true }
datafusion-ext-plans = { workspace = true }
log = "0.4.22"
object_store = "0.10.2"
prost = "0.13.0"

[build-dependencies]
tonic-build = "0.12.0"
