[package]
name = "datafusion-ext-plans"
version = "0.1.0"
edition = "2021"
resolver = "1"

[features]
default = ["tokio/rt-multi-thread"]

[dependencies]
arrow = { workspace = true }
async-trait = "0.1.81"
base64 = "0.22.1"
bitvec = "1.0.1"
byteorder = "1.5.0"
bytes = "1.6.1"
blaze-jni-bridge = { workspace = true }
bytesize = "1.1.0"
count-write = "0.1.0"
datafusion = { workspace = true }
datafusion-ext-commons = { workspace = true }
datafusion-ext-exprs = { workspace = true }
datafusion-ext-functions = { workspace = true }
derivative = "2.2.0"
futures = "0.3"
gxhash = "3.4.1"
hashbrown = "0.14.5"
itertools = "0.13.0"
jni = "0.20.0"
log = "0.4.22"
lz4_flex = "0.11.2"
num = "0.4.2"
object_store = "0.10.2"
once_cell = "1.19.0"
panic-message = "0.3.0"
parking_lot = "0.12.3"
paste = "1.0.15"
slimmer_box = "0.6.5"
smallvec = "1.13.2"
tempfile = "3"
tokio = "1.38"
uuid = "1.10.0"
zstd = "0.13.2"
